/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestioninventario;

/**
 *
 * @author usuario
 */
public class ActualizarLibro extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarLibro
     */
    public ActualizarLibro() {
        initComponents();
        jBtnGuardarActualizado.setVisible(false);
        jBtnCancelarActualizado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtTitulo = new javax.swing.JTextPane();
        jLblPrecio = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtPrecio = new javax.swing.JTextPane();
        jLblCantidad = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtCantidad = new javax.swing.JTextPane();
        jBtnAtras = new javax.swing.JButton();
        jLblTituloActualizar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtTituloActualizar = new javax.swing.JTextPane();
        jLblActualizar = new javax.swing.JLabel();
        jBtnBuscar = new javax.swing.JButton();
        jLblPrecioActualizado = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTxtPrecioActualizado = new javax.swing.JTextPane();
        jLblCantidadActualizado = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTxtCantidadActualizado = new javax.swing.JTextPane();
        jBtnGuardarActualizado = new javax.swing.JButton();
        jBtnCancelarActualizado = new javax.swing.JButton();
        jLblErrorActualizar = new javax.swing.JLabel();
        jLblErrorActualizar1 = new javax.swing.JLabel();

        jLblTitulo.setText("TÍTULO");

        jScrollPane1.setViewportView(jTxtTitulo);

        jLblPrecio.setText("PRECIO");

        jScrollPane3.setViewportView(jTxtPrecio);

        jLblCantidad.setText("CANTIDAD");

        jScrollPane4.setViewportView(jTxtCantidad);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnAtras.setBackground(new java.awt.Color(204, 204, 255));
        jBtnAtras.setText("ATRAS");
        jBtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtrasActionPerformed(evt);
            }
        });

        jLblTituloActualizar.setText("TÍTULO");

        jScrollPane2.setViewportView(jTxtTituloActualizar);

        jLblActualizar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLblActualizar.setForeground(new java.awt.Color(0, 102, 153));
        jLblActualizar.setText("ACTUALIZAR LIBRO");

        jBtnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        jBtnBuscar.setText("BUSCAR");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jLblPrecioActualizado.setText("PRECIO");

        jScrollPane5.setViewportView(jTxtPrecioActualizado);

        jLblCantidadActualizado.setText("CANTIDAD");

        jScrollPane6.setViewportView(jTxtCantidadActualizado);

        jBtnGuardarActualizado.setBackground(new java.awt.Color(204, 204, 255));
        jBtnGuardarActualizado.setText("GUARDAR");
        jBtnGuardarActualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActualizadoActionPerformed(evt);
            }
        });

        jBtnCancelarActualizado.setBackground(new java.awt.Color(204, 204, 255));
        jBtnCancelarActualizado.setText("CANCELAR");
        jBtnCancelarActualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActualizadoActionPerformed(evt);
            }
        });

        jLblErrorActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblErrorActualizar.setForeground(new java.awt.Color(255, 0, 0));

        jLblErrorActualizar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblErrorActualizar1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jBtnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblErrorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jLblTituloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jBtnGuardarActualizado)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jBtnAtras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtnCancelarActualizado))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblPrecioActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblCantidadActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLblActualizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLblErrorActualizar1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLblActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblTituloActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBuscar)
                    .addComponent(jLblErrorActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPrecioActualizado)
                    .addComponent(jLblCantidadActualizado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGuardarActualizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelarActualizado)
                    .addComponent(jBtnAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblErrorActualizar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtrasActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_jBtnAtrasActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        if (jTxtTituloActualizar.hashCode() == jTxtTitulo.hashCode()) {
            jBtnGuardarActualizado.setVisible(true);
            jBtnCancelarActualizado.setVisible(true);
        } else {
            jLblErrorActualizar1.setText("Este libro ya existe");
        }
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnGuardarActualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActualizadoActionPerformed
        jLblPrecioActualizado.setVisible(true);
        jLblCantidadActualizado.setVisible(true);
        jTxtPrecioActualizado.setVisible(true);
            jTxtPrecio.putClientProperty(jTxtPrecio, jTxtPrecioActualizado);
        jTxtCantidadActualizado.setVisible(true);
            jTxtCantidad.putClientProperty(jTxtCantidad, jTxtCantidadActualizado);
    }//GEN-LAST:event_jBtnGuardarActualizadoActionPerformed

    private void jBtnCancelarActualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActualizadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAtras;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnCancelarActualizado;
    private javax.swing.JButton jBtnGuardarActualizado;
    private javax.swing.JLabel jLblActualizar;
    private javax.swing.JLabel jLblCantidad;
    private javax.swing.JLabel jLblCantidadActualizado;
    private javax.swing.JLabel jLblErrorActualizar;
    private javax.swing.JLabel jLblErrorActualizar1;
    private javax.swing.JLabel jLblPrecio;
    private javax.swing.JLabel jLblPrecioActualizado;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblTituloActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane jTxtCantidad;
    private javax.swing.JTextPane jTxtCantidadActualizado;
    private javax.swing.JTextPane jTxtPrecio;
    private javax.swing.JTextPane jTxtPrecioActualizado;
    private javax.swing.JTextPane jTxtTitulo;
    private javax.swing.JTextPane jTxtTituloActualizar;
    // End of variables declaration//GEN-END:variables
}
